import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const IBMPlexMono = localFont({
  src: "./fonts/IBMPlexMonoRegular.ttf",
  variable: "--font-IBMPlexMono-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${IBMPlexMono.className}`}>{children}</body>
    </html>
  );
}
